language: java

jdk:
  - openjdk11


branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:

  - mkdir -p before-deploy # zip 에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy 로 이동후 전체 압축

  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/travis-test.zip


#  - zip -r travis-test *
#  - mkdir -p deploy
#  - mv travis-test.zip deploy/travis-test.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-test-temp
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-unitl-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-test-temp
    key: travis-test.zip
    bundle_type: zip
    application: travie-test-deploy1 # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: travis-test-deploy-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-unitl-deployed: true

notifications:
  email:
    recipients:
      - shineoov88@gmail.com